import { test } from '@playwright/test';

test('Capture Ivan Duri Service Card', async ({ page }) => {
    // 1. Navigate to the specific token generated by the seed script.
    // NOTE: In a real CI/CD, we would pass this token via env var, but for this specific "one-shot" verification 
    // requested by the user, we will paste the token we just generated.
    const token = '758565d6e095167ce9979be10f4e7d4ffc7ce6ae602b41b916a8c60712d9183d'; // From previous step output

    await page.goto(`/portal/${token}`);

    // 2. Wait for hydration and animation
    await page.waitForTimeout(3000);

    // 3. Take a full page screenshot to show the card in context
    await page.screenshot({ path: 'test-results/ivan-duri-card.png', fullPage: true });
});
